/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    plants: Plant;
    'plant-wishes': PlantWish;
    sowings: Sowing;
    'sowing-updates': SowingUpdate;
    tips: Tip;
    comments: Comment;
    reactions: Reaction;
    'sowing-follows': SowingFollow;
    reports: Report;
    pages: Page;
    'newsletter-issues': NewsletterIssue;
    'forum-categories': ForumCategory;
    'forum-topics': ForumTopic;
    'forum-replies': ForumReply;
    'month-intros': MonthIntro;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    plants: PlantsSelect<false> | PlantsSelect<true>;
    'plant-wishes': PlantWishesSelect<false> | PlantWishesSelect<true>;
    sowings: SowingsSelect<false> | SowingsSelect<true>;
    'sowing-updates': SowingUpdatesSelect<false> | SowingUpdatesSelect<true>;
    tips: TipsSelect<false> | TipsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    reactions: ReactionsSelect<false> | ReactionsSelect<true>;
    'sowing-follows': SowingFollowsSelect<false> | SowingFollowsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'newsletter-issues': NewsletterIssuesSelect<false> | NewsletterIssuesSelect<true>;
    'forum-categories': ForumCategoriesSelect<false> | ForumCategoriesSelect<true>;
    'forum-topics': ForumTopicsSelect<false> | ForumTopicsSelect<true>;
    'forum-replies': ForumRepliesSelect<false> | ForumRepliesSelect<true>;
    'month-intros': MonthIntrosSelect<false> | MonthIntrosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName: string;
  role: 'member' | 'moderator' | 'admin';
  /**
   * Quelques mots sur toi, ton potager.
   */
  bio?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Code pays/région (BE par défaut, pour le calendrier).
   */
  region?: string | null;
  newsletterOptIn?: boolean | null;
  reminderOptIn?: boolean | null;
  /**
   * Dernier envoi d'un rappel d'envie. Sert au throttle (max 1 mail / 48h / user).
   */
  lastWishReminderAt?: string | null;
  /**
   * Dernier envoi du digest hebdomadaire. Sert de borne pour calculer l'activité de la semaine.
   */
  lastDigestSentAt?: string | null;
  /**
   * Date où l'onboarding a été complété. Tant que c'est vide, /mon-potager/bienvenue prend le pas sur /mon-potager au login.
   */
  onboardedAt?: string | null;
  bannedAt?: string | null;
  /**
   * Anonymisation RGPD. PII effacée, contenu conservé.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    content?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Fiches maîtresses des espèces cultivables. Éditées par admins/modérateurs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants".
 */
export interface Plant {
  id: number;
  name: string;
  latinName?: string | null;
  /**
   * URL : /bibliotheque/<slug>
   */
  slug: string;
  /**
   * Catégorie principale pour filtrer dans la bibliothèque (une seule).
   */
  category?:
    | (
        | 'legume-fruit'
        | 'legume-feuille'
        | 'legume-racine'
        | 'legume-bulbe'
        | 'legume-tige'
        | 'legume-fleur'
        | 'aromatique'
        | 'fleur'
        | 'petit-fruit'
        | 'arbre-fruitier'
        | 'engrais-vert'
        | 'exotique-interieur'
      )
    | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sowingWindow: {
    startMonth: '01' | '02' | '03' | '04' | '05' | '06' | '07' | '08' | '09' | '10' | '11' | '12';
    endMonth: '01' | '02' | '03' | '04' | '05' | '06' | '07' | '08' | '09' | '10' | '11' | '12';
    /**
     * Ex. "intérieur en mars, extérieur dès mai".
     */
    note?: string | null;
  };
  /**
   * Étapes que cette plante traverse, dans l'ordre. Sert pour la timeline et les rappels.
   */
  typicalStages?:
    | {
        stage:
          | 'semis'
          | 'levee'
          | 'eclaircissage'
          | 'repiquage'
          | 'endurcissement'
          | 'mise-en-terre'
          | 'tuteurage'
          | 'floraison'
          | 'recolte';
        daysFromPrevious?: number | null;
        tip?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Plantes qui se plaisent à côté de celle-ci (pluriculture / compagnonnage). Indique pourquoi.
   */
  companions?:
    | {
        plant: number | Plant;
        /**
         * Ex. « repousse les pucerons », « apporte de l'ombre », « fixe l'azote pour... »
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Plantes à éviter à côté de celle-ci (mêmes maladies, allélopathie, concurrence, etc.).
   */
  incompatibles?:
    | {
        plant: number | Plant;
        /**
         * Ex. « mêmes maladies (mildiou) », « allélopathie », « inhibe la fixation d'azote »
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedTips?: (number | Tip)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Conseils & astuces. En MVP v1, créés par les admins/modérateurs uniquement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tips".
 */
export interface Tip {
  id: number;
  title: string;
  slug: string;
  /**
   * 1-3 phrases. Sert de description SEO (Google + partages sociaux) et d'accroche sous le titre. Idéal : 140-160 caractères.
   */
  excerpt?: string | null;
  /**
   * Catégorie principale. Détermine la page /tips/categorie/<slug> où ce tip apparaîtra.
   */
  category?: ('semis' | 'sol' | 'arrosage' | 'maladies' | 'recolte' | 'outils' | 'associations' | 'saisons') | null;
  author: number | User;
  coverImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Plantes concernées (optionnel — laisse vide si général).
   */
  plants?: (number | Plant)[] | null;
  status: 'published' | 'draft' | 'flagged';
  updatedAt: string;
  createdAt: string;
}
/**
 * Envies de semis posées depuis la bibliothèque. Une ligne = (user, plante).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-wishes".
 */
export interface PlantWish {
  id: number;
  user: number | User;
  plant: number | Plant;
  /**
   * Année de la dernière notif envoyée. Empêche le re-spam la même saison.
   */
  lastNotifiedYear?: number | null;
  /**
   * Mis à true si le user clique "pas cette année". Empêche le rappel sans supprimer l'envie.
   */
  dismissed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Un lot de semis (ex. 'Mes courgettes 2026') tenu par un membre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sowings".
 */
export interface Sowing {
  id: number;
  name: string;
  owner: number | User;
  plant: number | Plant;
  startedAt: string;
  visibility: 'public' | 'private';
  /**
   * Dérivé automatiquement de la dernière SowingUpdate taguée.
   */
  currentStage?: string | null;
  reminderSettings?: {
    enabled?: boolean | null;
  };
  /**
   * Dernière étape pour laquelle un rappel a été envoyé. Bloque les doublons.
   */
  lastReminderStage?: string | null;
  lastReminderAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Une entrée datée du journal (photo + note, étape optionnelle).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sowing-updates".
 */
export interface SowingUpdate {
  id: number;
  sowing: number | Sowing;
  author: number | User;
  date: string;
  note?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photos?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optionnel : tague cette mise à jour à une étape (semis, repiquage, récolte…).
   */
  stage?:
    | (
        | 'semis'
        | 'levee'
        | 'eclaircissage'
        | 'repiquage'
        | 'endurcissement'
        | 'mise-en-terre'
        | 'tuteurage'
        | 'floraison'
        | 'recolte'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  author: number | User;
  /**
   * Cible du commentaire (un Sowing, une mise à jour, ou un Tip).
   */
  target:
    | {
        relationTo: 'sowings';
        value: number | Sowing;
      }
    | {
        relationTo: 'sowing-updates';
        value: number | SowingUpdate;
      }
    | {
        relationTo: 'tips';
        value: number | Tip;
      };
  body: string;
  status: 'visible' | 'flagged' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions".
 */
export interface Reaction {
  id: number;
  user: number | User;
  sowingUpdate: number | SowingUpdate;
  kind: 'heart';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sowing-follows".
 */
export interface SowingFollow {
  id: number;
  user: number | User;
  sowing: number | Sowing;
  /**
   * Dernière update pour laquelle on a déjà envoyé un email. Sert d'anti-doublon.
   */
  lastNotifiedUpdate?: (number | null) | SowingUpdate;
  updatedAt: string;
  createdAt: string;
}
/**
 * File d'attente de modération. Triable par statut.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  reporter: number | User;
  target:
    | {
        relationTo: 'sowings';
        value: number | Sowing;
      }
    | {
        relationTo: 'sowing-updates';
        value: number | SowingUpdate;
      }
    | {
        relationTo: 'comments';
        value: number | Comment;
      }
    | {
        relationTo: 'tips';
        value: number | Tip;
      }
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'forum-topics';
        value: number | ForumTopic;
      }
    | {
        relationTo: 'forum-replies';
        value: number | ForumReply;
      };
  reason: 'spam' | 'inappropriate' | 'harassment' | 'misinformation' | 'other';
  note?: string | null;
  status: 'open' | 'resolved' | 'dismissed';
  updatedAt: string;
  createdAt: string;
}
/**
 * Sujets du forum.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-topics".
 */
export interface ForumTopic {
  id: number;
  title: string;
  slug: string;
  category: number | ForumCategory;
  author: number | User;
  /**
   * Corps du sujet en markdown.
   */
  body: string;
  /**
   * Épinglé en haut de la catégorie.
   */
  pinned?: boolean | null;
  /**
   * Bloque les nouvelles réponses.
   */
  locked?: boolean | null;
  /**
   * Compteur dénormalisé, mis à jour par hook.
   */
  replyCount?: number | null;
  /**
   * Pour le tri "fil chaud".
   */
  lastReplyAt?: string | null;
  status: 'visible' | 'flagged' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * Catégories du forum. Fixes — éditées par les admins uniquement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-categories".
 */
export interface ForumCategory {
  id: number;
  name: string;
  /**
   * URL : /forum/<slug>
   */
  slug: string;
  /**
   * Une ligne affichée sous le titre.
   */
  description?: string | null;
  /**
   * Un emoji court, ex. 🌿
   */
  icon?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Réponses aux sujets du forum.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-replies".
 */
export interface ForumReply {
  id: number;
  topic: number | ForumTopic;
  author: number | User;
  /**
   * Corps de la réponse en markdown.
   */
  body: string;
  status: 'visible' | 'flagged' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * Pages éditoriales (Accueil, À propos, Contact, Mentions légales, Confidentialité…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Sans le slash (ex. 'a-propos', 'mentions-legales').
   */
  slug: string;
  intro?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Archive des numéros mensuels envoyés via Resend Broadcasts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-issues".
 */
export interface NewsletterIssue {
  id: number;
  /**
   * Format YYYY-MM (ex. '2026-05').
   */
  month: string;
  subject: string;
  /**
   * Snapshot HTML envoyé (généré au moment du broadcast).
   */
  htmlSnapshot?: string | null;
  resendBroadcastId?: string | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Texte d'intro affiché en haut de chaque page mois du calendrier de semis.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "month-intros".
 */
export interface MonthIntro {
  id: number;
  /**
   * Un seul document par mois. Sert de clé.
   */
  month: '01' | '02' | '03' | '04' | '05' | '06' | '07' | '08' | '09' | '10' | '11' | '12';
  /**
   * Phrase d'accroche (2-3 phrases) qui plante le décor du mois. Affichée sous le H1.
   */
  intro: string;
  /**
   * Bloc plus long, affiché en bas de page mois — conseils, anecdotes, ce que tu veux mettre en avant.
   */
  extra?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'plants';
        value: number | Plant;
      } | null)
    | ({
        relationTo: 'plant-wishes';
        value: number | PlantWish;
      } | null)
    | ({
        relationTo: 'sowings';
        value: number | Sowing;
      } | null)
    | ({
        relationTo: 'sowing-updates';
        value: number | SowingUpdate;
      } | null)
    | ({
        relationTo: 'tips';
        value: number | Tip;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'reactions';
        value: number | Reaction;
      } | null)
    | ({
        relationTo: 'sowing-follows';
        value: number | SowingFollow;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      } | null)
    | ({
        relationTo: 'forum-categories';
        value: number | ForumCategory;
      } | null)
    | ({
        relationTo: 'forum-topics';
        value: number | ForumTopic;
      } | null)
    | ({
        relationTo: 'forum-replies';
        value: number | ForumReply;
      } | null)
    | ({
        relationTo: 'month-intros';
        value: number | MonthIntro;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  region?: T;
  newsletterOptIn?: T;
  reminderOptIn?: T;
  lastWishReminderAt?: T;
  lastDigestSentAt?: T;
  onboardedAt?: T;
  bannedAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        content?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants_select".
 */
export interface PlantsSelect<T extends boolean = true> {
  name?: T;
  latinName?: T;
  slug?: T;
  category?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  description?: T;
  sowingWindow?:
    | T
    | {
        startMonth?: T;
        endMonth?: T;
        note?: T;
      };
  typicalStages?:
    | T
    | {
        stage?: T;
        daysFromPrevious?: T;
        tip?: T;
        id?: T;
      };
  companions?:
    | T
    | {
        plant?: T;
        note?: T;
        id?: T;
      };
  incompatibles?:
    | T
    | {
        plant?: T;
        note?: T;
        id?: T;
      };
  relatedTips?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-wishes_select".
 */
export interface PlantWishesSelect<T extends boolean = true> {
  user?: T;
  plant?: T;
  lastNotifiedYear?: T;
  dismissed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sowings_select".
 */
export interface SowingsSelect<T extends boolean = true> {
  name?: T;
  owner?: T;
  plant?: T;
  startedAt?: T;
  visibility?: T;
  currentStage?: T;
  reminderSettings?:
    | T
    | {
        enabled?: T;
      };
  lastReminderStage?: T;
  lastReminderAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sowing-updates_select".
 */
export interface SowingUpdatesSelect<T extends boolean = true> {
  sowing?: T;
  author?: T;
  date?: T;
  note?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  stage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tips_select".
 */
export interface TipsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  author?: T;
  coverImage?: T;
  body?: T;
  plants?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  author?: T;
  target?: T;
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions_select".
 */
export interface ReactionsSelect<T extends boolean = true> {
  user?: T;
  sowingUpdate?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sowing-follows_select".
 */
export interface SowingFollowsSelect<T extends boolean = true> {
  user?: T;
  sowing?: T;
  lastNotifiedUpdate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reporter?: T;
  target?: T;
  reason?: T;
  note?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-issues_select".
 */
export interface NewsletterIssuesSelect<T extends boolean = true> {
  month?: T;
  subject?: T;
  htmlSnapshot?: T;
  resendBroadcastId?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-categories_select".
 */
export interface ForumCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-topics_select".
 */
export interface ForumTopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  author?: T;
  body?: T;
  pinned?: T;
  locked?: T;
  replyCount?: T;
  lastReplyAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-replies_select".
 */
export interface ForumRepliesSelect<T extends boolean = true> {
  topic?: T;
  author?: T;
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "month-intros_select".
 */
export interface MonthIntrosSelect<T extends boolean = true> {
  month?: T;
  intro?: T;
  extra?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}